"""Session persistence (Phase R-MVP TR.1 skeleton, hardened in TR.8).

The host's `~/.dscore.ttc.playwright-agent/recordings/<id>/` is the source of truth.
The container mounts the same directory at `/data/recordings/<id>/`.

This module only handles directory creation, path computation, and simple
metadata storage. TR.8 reinforces mount verification and session-list sync.
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path
from typing import Optional


DEFAULT_HOST_RECORDINGS_DIR = os.path.expanduser(
    "~/.dscore.ttc.playwright-agent/recordings"
)


def host_root() -> Path:
    """Host-side recordings root. Overridable via env `RECORDING_HOST_ROOT`."""
    return Path(os.environ.get("RECORDING_HOST_ROOT", DEFAULT_HOST_RECORDINGS_DIR))


def session_dir(session_id: str) -> Path:
    """Return `<host_root>/<session_id>/` and create the directory."""
    p = host_root() / session_id
    p.mkdir(parents=True, exist_ok=True)
    return p


def container_path_for(session_id: str) -> str:
    """Path as seen from inside the container, used in docker exec calls.

    TR.8 decision: nested bind mounts on top of a `/data` named volume have
    weak docker guarantees, so we use a **dedicated mount point `/recordings`**.
    Add `-v <host_recordings>:/recordings:rw` to the docker run in build.sh.

    Overridable via env `RECORDING_CONTAINER_ROOT` (for per-environment tweaks).
    """
    base = os.environ.get("RECORDING_CONTAINER_ROOT", "/recordings")
    return f"{base}/{session_id}"


def save_metadata(session_id: str, meta: dict) -> Path:
    """Save `<session_dir>/metadata.json`."""
    d = session_dir(session_id)
    path = d / "metadata.json"
    path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
    return path


def load_metadata(session_id: str) -> Optional[dict]:
    p = session_dir(session_id) / "metadata.json"
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def scenario_path(session_id: str) -> Path:
    """Host-side path to the converted scenario.json."""
    return session_dir(session_id) / "scenario.json"


def original_py_path(session_id: str) -> Path:
    """Host-side path to the original codegen .py output."""
    return session_dir(session_id) / "original.py"


def regression_py_path(session_id: str) -> Path:
    """Regression test .py auto-generated by the executor from scenario.healed.json."""
    return session_dir(session_id) / "regression_test.py"


def run_log_path(session_id: str) -> Path:
    """Per-step PASS/HEALED/FAIL records (jsonl) written after a Play run."""
    return session_dir(session_id) / "run_log.jsonl"


def load_scenario(session_id: str) -> Optional[list]:
    p = scenario_path(session_id)
    if not p.exists():
        return None
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
        if not isinstance(data, list):
            return None
        return data
    except (OSError, json.JSONDecodeError):
        return None


def delete_session(session_id: str) -> bool:
    """Remove the entire session directory. False if it does not exist."""
    import shutil
    d = host_root() / session_id
    if not d.exists():
        return False
    shutil.rmtree(d, ignore_errors=True)
    return True


def now_iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%S%z", time.localtime())


def list_session_dirs() -> list[str]:
    """List session IDs (directory names) under the host persistence root.

    Sessions on disk survive a server restart. Used so the UI's "Recent sessions"
    table can absorb on-disk sessions at startup.
    """
    root = host_root()
    if not root.exists():
        return []
    return sorted(
        [p.name for p in root.iterdir() if p.is_dir()],
    )
