#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ==================================================================================
# File: gitlab_issue_creator.py
# Version: 1.1
#
# [Overview]
# This script handles **stage 3 (auto-register issues into the issue tracker)**
# of the quality analysis pipeline (Phase 3). It reads the LLM analysis output
# (JSONL) from dify_sonar_issue_analyzer.py and automatically creates an issue
# for each entry in the GitLab project's issue tracker.
#
# [Position in the pipeline]
# dify_sonar_issue_analyzer.py (AI analysis)
#       ↓ llm_analysis.jsonl
# >>> gitlab_issue_creator.py (issue registration) <<<
#       ↓ gitlab_issues_created.json (registration result summary)
#
# [Core features]
# 1. Reads the JSONL output line by line and converts each entry to a GitLab issue.
# 2. Issue title is unified to "[severity] issue message" format.
# 3. Replaces SonarQube internal URLs with externally accessible URLs.
# 4. Skips creation if an issue with the same SonarQube key already exists
#    (deduplication).
# 5. Saves create/skip/fail counts to a JSON file for pipeline tracing.
#
# [Run example]
# python3 gitlab_issue_creator.py \
#   --gitlab-host-url http://gitlab:80 \
#   --gitlab-token glpat-xxxxx \
#   --gitlab-project mygroup/myproject \
#   --input llm_analysis.jsonl \
#   --sonar-public-url http://localhost:9000
# ==================================================================================

import argparse
import base64
import json
import sys
import time
import re
from urllib.parse import urlencode, urljoin, quote
from urllib.request import Request, urlopen
from urllib.error import HTTPError, URLError


def _http_post_form(url: str, headers: dict, form: dict, timeout: int = 60):
    """
    POST URL-encoded form data.

    The GitLab Issues API is more reliable with
    application/x-www-form-urlencoded than with JSON, so we send via form
    encoding.

    Args:
        url: GitLab API endpoint
        headers: auth headers including PRIVATE-TOKEN
        form: form fields to send (title, description, labels, ...)
        timeout: request timeout (seconds)

    Returns:
        tuple: (HTTP status code, response body string)
    """
    data = urlencode(form, doseq=True).encode("utf-8")
    h = dict(headers or {})
    h["Content-Type"] = "application/x-www-form-urlencoded"
    req = Request(url, headers=h, method="POST", data=data)
    with urlopen(req, timeout=timeout) as resp:
        body = resp.read().decode("utf-8", errors="replace")
        return resp.status, body


def _http_get_json(url: str, headers: dict, timeout: int = 60) -> dict:
    """
    Send an HTTP GET and return the parsed JSON response.

    Used for GitLab Issues search API calls (such as duplicate detection).
    """
    req = Request(url, headers=headers, method="GET")
    with urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8", errors="replace"))


def _replace_sonar_url(text: str, sonar_host_url: str, sonar_public_url: str) -> str:
    """
    Replace SonarQube URLs inside the LLM-generated markdown with the
    externally accessible URL.

    Catches both the container-internal URL and variants the LLM may
    arbitrarily reconstruct (for example keeping the internal port but
    swapping the hostname to localhost), normalizing them all to the
    user-accessible public URL (e.g. the docker-compose host-mapped port).

    Replacement targets (all rewritten to the same public base):
      1. The sonar_host_url parameter (e.g. http://127.0.0.1:9000, http://sonarqube:9000)
      2. Common internal hostname variants: http://sonarqube:9000,
         http://127.0.0.1:9000, http://localhost:9000
         (frequently produced by the LLM when reconstructing context)
      3. Relative paths starting with '/project/issues?' → prepended with the public host

    Args:
        text: markdown text generated by the LLM (issue description)
        sonar_host_url: SonarQube internal URL used by Jenkins
        sonar_public_url: SonarQube external URL accessible to users

    Returns:
        Text with URLs replaced
    """
    if not text: return text
    target_base = (sonar_public_url or "http://localhost:9000").rstrip("/")
    # Normalize the explicit internal URL plus the common variants.
    internal_variants = set()
    if sonar_host_url:
        internal_variants.add(sonar_host_url.rstrip("/"))
    # Variants the LLM frequently reconstructs — swaps the hostname while keeping the internal port
    internal_variants.update([
        "http://sonarqube:9000",
        "http://127.0.0.1:9000",
        "http://localhost:9000",
    ])
    # Drop the target itself so we do not replace it with itself.
    internal_variants.discard(target_base)
    for variant in internal_variants:
        text = text.replace(variant, target_base)
    # Prepend the host to relative-path SonarQube links.
    # The lookbehinds skip cases where http: or https: already precedes them.
    pattern = r"(?<!http:)(?<!https:)(?<![a-zA-Z0-9])(/project/issues\?)"
    text = re.sub(pattern, f"{target_base}\\1", text)
    return text


def _gitlab_blob_url(public_base: str, project: str, branch: str, path: str, line: int) -> str:
    """Build a GitLab direct file link, including the line anchor.

    Example: http://localhost:28090/root/dscore-ttc-sample/-/blob/main/src/auth.py#L24
    """
    if not public_base or not project or not path:
        return ""
    base = public_base.rstrip("/")
    anchor = f"#L{line}" if isinstance(line, int) and line > 0 else ""
    return f"{base}/{project}/-/blob/{branch or 'main'}/{path}{anchor}"


def _gitlab_commit_url(public_base: str, project: str, sha: str) -> str:
    """Build a GitLab commit link.

    Example: http://localhost:28090/root/dscore-ttc-sample/-/commit/abc1234
    """
    if not public_base or not project or not sha:
        return ""
    base = public_base.rstrip("/")
    return f"{base}/{project}/-/commit/{sha}"


def _short_sha(sha: str, n: int = 8) -> str:
    return sha[:n] if sha else ""


# ─ Rule description English translation (Ollama gemma4) ───────────────────
# Module-level dict cache keyed by rule_key. The same rule shared across
# multiple issues is translated only once.
# On translation failure / Ollama unavailable / empty input, the original
# English text is returned (graceful fallback).
# Translation result is the only form shown in the GitLab issue body — the
# original is available via the SonarQube link.
_rule_translation_cache: dict = {}


def _translate_rule_to_english(rule_key: str, rule_desc: str,
                              ollama_base_url: str, ollama_model: str,
                              timeout: int = 60) -> str:
    """Polish the Sonar rule description into clear English. Returns the
    original on failure.

    Cache key: rule_key — the same rule shares the same description across
    issues, so we translate once and reuse.
    Ollama API: POST {base}/api/chat (Ollama standard).
    """
    if not rule_desc or not rule_desc.strip():
        return rule_desc
    if not ollama_base_url or not ollama_model:
        return rule_desc
    if rule_key in _rule_translation_cache:
        return _rule_translation_cache[rule_key]

    # Cap very long descriptions (protects Ollama inference time).
    src = rule_desc.strip()[:4000]
    system_msg = (
        "You are an editor that polishes SonarQube static-analysis rule descriptions into clear English.\n"
        "Rules:\n"
        "- Never modify code blocks (```...```) or inline code (`...`); keep them verbatim.\n"
        "- Preserve any HTML tags as-is; only the text inside is rewritten.\n"
        "- Use natural English — no literal translation, paraphrase when needed.\n"
        "- No preamble (e.g. 'Translation:', 'English:'), no trailer, no meta commentary. Output only the rewritten body.\n"
        "- Keep SonarQube standard terminology (e.g. 'Noncompliant Code Example', 'Compliant Solution') unchanged."
    )
    body = {
        "model": ollama_model,
        "messages": [
            {"role": "system", "content": system_msg},
            {"role": "user", "content": src},
        ],
        "stream": False,
        "options": {
            "temperature": 0.1,
            "num_predict": 2048,
        },
    }
    url = ollama_base_url.rstrip("/") + "/api/chat"
    try:
        req = Request(
            url, method="POST",
            data=json.dumps(body).encode("utf-8"),
            headers={"Content-Type": "application/json"},
        )
        with urlopen(req, timeout=timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        translated = (data.get("message", {}) or {}).get("content", "").strip()
        if not translated or len(translated) < 20:
            # Translation too short or empty — treat as failure.
            _rule_translation_cache[rule_key] = rule_desc
            return rule_desc
        _rule_translation_cache[rule_key] = translated
        return translated
    except Exception as e:
        print(f"[rule-translate:WARN] {rule_key} — {e} — keeping original", file=sys.stderr)
        _rule_translation_cache[rule_key] = rule_desc
        return rule_desc


def _sonar_add_comment(sonar_host: str, sonar_token: str, issue_key: str,
                       text: str, timeout: int = 30) -> tuple:
    """Attach the LLM fp_reason as a comment via SonarQube `POST /api/issues/add_comment`.

    Called right before the false_positive transition so analysts can
    immediately see "why this is a false positive" in the Sonar UI. The
    transition itself is a separate call (do_transition). Even if this
    fails the transition is still attempted — the comment is value-add,
    not a gate.

    Empty text / token → silent skip (sonar-token may be unset in some
    environments).
    """
    if not sonar_host or not sonar_token or not issue_key or not (text or "").strip():
        return (False, "missing sonar_host / token / issue_key / text")
    url = f"{sonar_host.rstrip('/')}/api/issues/add_comment"
    form = urlencode({"issue": issue_key, "text": text.strip()}).encode("utf-8")
    auth = "Basic " + base64.b64encode(f"{sonar_token}:".encode("utf-8")).decode("ascii")
    headers = {
        "Authorization": auth,
        "Content-Type": "application/x-www-form-urlencoded",
    }
    req = Request(url, method="POST", headers=headers, data=form)
    try:
        with urlopen(req, timeout=timeout) as resp:
            if 200 <= resp.status < 300:
                return (True, "")
            body = resp.read().decode("utf-8", errors="replace")
            return (False, f"HTTP {resp.status} · {body[:200]}")
    except HTTPError as e:
        body = e.read().decode("utf-8", errors="replace") if hasattr(e, "read") else ""
        return (False, f"HTTP {e.code} · {body[:200]}")
    except URLError as e:
        return (False, f"URLError: {e}")
    except Exception as e:
        return (False, f"Exception: {e}")


def _sonar_mark_fp(sonar_host: str, sonar_token: str, issue_key: str, timeout: int = 30) -> tuple:
    """Step D — mark the issue as false positive via `POST /api/issues/do_transition`.

    Behavior on Community Edition varies between environments, so even on
    failure the pipeline continues (Dual-path design). Returns:
    `(success: bool, err_msg: str)`.

    Auth: Basic auth with token as username, empty password (Sonar standard).
    """
    if not sonar_host or not sonar_token or not issue_key:
        return (False, "missing sonar_host / token / issue_key")
    url = f"{sonar_host.rstrip('/')}/api/issues/do_transition"
    form = urlencode({"issue": issue_key, "transition": "falsepositive"}).encode("utf-8")
    auth = "Basic " + base64.b64encode(f"{sonar_token}:".encode("utf-8")).decode("ascii")
    headers = {
        "Authorization": auth,
        "Content-Type": "application/x-www-form-urlencoded",
    }
    req = Request(url, method="POST", headers=headers, data=form)
    try:
        with urlopen(req, timeout=timeout) as resp:
            if 200 <= resp.status < 300:
                return (True, "")
            body = resp.read().decode("utf-8", errors="replace")
            return (False, f"HTTP {resp.status} · {body[:200]}")
    except HTTPError as e:
        body = e.read().decode("utf-8", errors="replace") if hasattr(e, "read") else ""
        return (False, f"HTTP {e.code} · {body[:200]}")
    except URLError as e:
        return (False, f"URLError: {e}")
    except Exception as e:
        return (False, f"Exception: {e}")


def _merge_labels(llm_labels, severity: str, classification: str, confidence: str,
                  llm_skipped: bool, extra: list = None) -> str:
    """Step D — assemble labels. Merges LLM suggestions + Step B/C fields +
    Step D warning labels, dedup'd.

    Returns: "labelA,labelB,..." string (GitLab Issues API form format).
    """
    merged = []
    if isinstance(llm_labels, list):
        merged.extend(str(x) for x in llm_labels if x)
    elif llm_labels:
        merged.append(str(llm_labels))

    if severity:
        merged.append(f"severity:{severity}")
    if classification:
        merged.append(f"classification:{classification}")
    if confidence:
        merged.append(f"confidence:{confidence}")
    if llm_skipped:
        merged.append("auto_template:true")
    if extra:
        merged.extend(extra)

    # Dedup (preserves order)
    seen = set()
    out = []
    for lbl in merged:
        if lbl and lbl not in seen:
            seen.add(lbl)
            out.append(lbl)
    return ",".join(out)


def _trim_code_snippet(snippet: str, target_line: int, context: int = 10) -> str:
    """Reduce the snippet (±50 lines from exporter) down to ±context lines around the issue line.

    Snippet line format: "{marker}{lineno:>5} | {code}" (produced by sonar_issue_exporter).
    Body readability — shrinks the full 101 lines to roughly 21.
    """
    if not snippet:
        return snippet
    lines = snippet.splitlines()
    if not lines:
        return snippet
    # Find the line index containing target_line (parse lineno)
    target_idx = None
    for i, ln in enumerate(lines):
        try:
            # Pull 24 from "   24 | code"
            parts = ln.split("|", 1)[0].strip().split()
            num = int(parts[-1])
            if num == target_line:
                target_idx = i
                break
        except Exception:
            continue
    if target_idx is None:
        return snippet  # cannot find the line → keep original
    lo = max(0, target_idx - context)
    hi = min(len(lines), target_idx + context + 1)
    return "\n".join(lines[lo:hi])


def _action_verdict(severity: str, classification: str, confidence: str,
                    cited_count: int, total_used: int) -> tuple:
    """Phase C — PM-friendly action verdict signal.

    Combines severity / classification / confidence + RAG citation context to
    compress "what should I do now" into a single line. PMs can prioritize
    just by reading the first line of the body.

    Returns: (emoji, one-line label, one-line rationale).
    """
    sev = (severity or "").upper()
    cls = (classification or "").lower()
    conf = (confidence or "").lower()
    no_context = total_used == 0
    weak_basis = (no_context or (cited_count == 0 and conf in ("low", ""))) and cls != "false_positive"

    # false_positive is low priority (especially when confidence high — confidently a false positive)
    if cls == "false_positive":
        if conf == "high":
            return ("⚪", "Likely false positive (high confidence)",
                    "AI judges this a SonarQube misjudgment. Ignore or mark FP on the Sonar side.")
        return ("⚪", "Likely false positive",
                "AI suspects this is a false positive — let a developer review then mark FP or fix.")

    if cls == "wont_fix":
        return ("🟢", "Safe to ignore (technical debt)",
                "Real issue, but low priority for the cost. Add to backlog and address later.")

    # true_positive or empty value — color depends on severity + basis.
    if sev in ("BLOCKER", "CRITICAL"):
        if weak_basis:
            return ("🟠", "Recommend immediate fix (AI evidence weak)",
                    "Severity is high, recommend immediate action. AI relied on general principles, "
                    "**so a developer should verify the code context directly** before fixing.")
        return ("🔴", "Fix immediately",
                "High severity + AI evidence is solid. This issue should be handled first.")

    if sev == "MAJOR":
        if weak_basis:
            return ("🟡", "Review then fix",
                    "AI evidence is weak — let a developer review and decide whether to fix.")
        return ("🟡", "Review then fix",
                "Medium severity — recommend handling within the next sprint.")

    # MINOR / INFO
    if sev in ("MINOR", "INFO"):
        return ("🟢", "Low priority",
                "Low severity — handle alongside general code cleanup.")

    # No severity (e.g. auto_template case)
    return ("⚪", "Needs further review",
            "Severity info is missing — recommend a developer assesses the priority.")


def _location_natural_text(rel_path: str, line_int: int, enclosing_fn: str,
                            enclosing_kind: str) -> str:
    """Phase C — render the location as a single natural-language line. PM-friendly."""
    if not rel_path:
        return "(no file location info)"
    fn_part = ""
    if enclosing_fn:
        kind_word = {
            "method": "method", "function": "function", "class": "class",
            "type": "type", "interface": "interface",
        }.get(enclosing_kind, "function")
        fn_part = f", in the `{enclosing_fn}` {kind_word}"
    return f"`{rel_path}` (line {line_int}){fn_part}"


def _format_static_context_pm(row: dict) -> str:
    """Phase C — PM-friendly static metadata display. Surface the enclosing
    function's HTTP route, decorators, parameters, etc. as 1-3 natural-language
    lines. Returns empty string if nothing applies.
    """
    lines = []
    endpoint = (row.get("enclosing_endpoint") or "").strip()
    decorators = row.get("enclosing_decorators") or []
    params = row.get("enclosing_doc_params") or []

    if endpoint:
        lines.append(f"- 🌐 Externally exposed: reachable via the HTTP `{endpoint}` endpoint.")
    if decorators:
        # Pull only the identifier (`@app.route('/x')` → `app.route`)
        dec_idents = []
        for d in decorators[:3]:
            if isinstance(d, str):
                body = d.lstrip("@").split("(", 1)[0].strip()
                if body:
                    dec_idents.append(f"`@{body}`")
        if dec_idents:
            lines.append(f"- 🛡️ Static intent applied: {', '.join(dec_idents)}")
    if params:
        names = []
        for p in params[:5]:
            if isinstance(p, (list, tuple)) and len(p) >= 2 and p[1]:
                names.append(f"`{p[1]}`")
        if names:
            lines.append(f"- 📝 Input parameters: {', '.join(names)}")
    return "\n".join(lines)


def _format_ai_basis_pm(row: dict) -> str:
    """Phase C — 'AI judgment basis' section. Surfaces the pre-training → answer
    causality to PMs.

    Summarizes the rag_diagnostic used_items + tree_sitter_hits in natural language.
    """
    diag = row.get("rag_diagnostic") or {}
    if not diag:
        # skip_llm or no diagnostic available — short notice
        if row.get("llm_skipped"):
            return "_(Auto-template response — no RAG analysis. Direct developer review recommended.)_"
        return ""

    used_items = diag.get("used_items") or []
    citation = diag.get("citation") or {}
    cited = citation.get("cited_count", 0) or 0
    total_used = citation.get("total_used", 0) or 0
    ts = diag.get("tree_sitter_hits") or {}
    ts_total = ts.get("total_hits", 0) or 0

    lines = []

    if total_used == 0:
        lines.append(
            "- ⚠️ The AI generated this answer without receiving any related code chunks from our project. "
            "This analysis relied on **general principles and the rule description**, "
            "and project-specific specifics may not be reflected."
        )
        return "\n".join(lines)

    # 1) Referenced code — group used_items' path::symbol by category as natural language
    callers = [it for it in used_items if it.get("bucket") == "callers"]
    tests = [it for it in used_items if it.get("bucket") == "tests"]
    others = [it for it in used_items if it.get("bucket") == "others"]

    def _refs(items, limit=3):
        out = []
        for it in items[:limit]:
            sym = it.get("symbol", "")
            path = it.get("path", "")
            if sym and sym != "?":
                out.append(f"`{sym}`")
            elif path and path != "?":
                out.append(f"`{path.rsplit('/', 1)[-1]}`")
        return out

    parts = []
    if callers:
        cs = _refs(callers)
        if cs:
            parts.append(f"{len(callers)} calling functions ({', '.join(cs)})")
    if tests:
        ts_refs = _refs(tests)
        if ts_refs:
            parts.append(f"{len(tests)} related tests ({', '.join(ts_refs)})")
    if others:
        os_refs = _refs(others)
        if os_refs:
            parts.append(f"{len(others)} other related code ({', '.join(os_refs)})")

    if parts:
        lines.append(f"- 🔎 Project code referenced: {' · '.join(parts)}")

    # 2) Citation context — cited / total
    if total_used > 0:
        rate = cited * 100.0 / total_used
        if rate >= 60:
            lines.append(
                f"- ✅ AI cited {cited} out of {total_used} chunks directly in the answer "
                f"({rate:.0f}%). Solid evidence."
            )
        elif rate >= 30:
            lines.append(
                f"- 🟡 AI cited only {cited} of {total_used} chunks in the answer "
                f"({rate:.0f}%). Evidence partially used."
            )
        elif cited == 0:
            lines.append(
                f"- ⚠️ AI did not cite any of the {total_used} chunks it received — "
                "the answer may have leaned on general principles, recommend direct review."
            )

    # 3) Static metadata usage — tree_sitter_hits
    if ts_total > 0:
        sigs = []
        if ts.get("endpoint_hits"):
            sigs.append("HTTP route")
        if ts.get("decorator_hits"):
            sigs.append("decorator")
        if ts.get("param_hits"):
            sigs.append("parameter names")
        if ts.get("rag_meta_hits"):
            sigs.append("RAG chunk meta")
        if sigs:
            lines.append(
                f"- 📚 Pre-training static metadata used: {', '.join(sigs)} ({ts_total} citations). "
                "AI answer directly reflects our project's vocabulary and structure."
            )

    return "\n".join(lines)


def render_issue_body(row: dict, args) -> str:
    """Phase C — PM-friendly GitLab Issue body redesign.

    Shifted from developer-friendly to PM-friendly:
    - Top: 🚦 Action Verdict — combined severity/false-positive/evidence signal
    - 📌 What is the problem (LLM one-line summary)
    - 🎯 Where does it happen (natural-language location + static context)
    - ⚠️ Impact and reasons (LLM impact_analysis)
    - 🛠️ How to fix (LLM suggested_fix + diff)
    - 🔍 AI judgment basis (NEW — pre-training utilization causality)
    - 📂 Other locations of the same pattern (conditional)
    - 📖 Technical detail (▶ collapsed — code block / Rule key / all links)
    """
    outputs = row.get("outputs") or {}
    rel_path = row.get("relative_path", "") or ""
    line = row.get("line") or 0
    try:
        line_int = int(line) if line else 0
    except Exception:
        line_int = 0
    enclosing_fn = row.get("enclosing_function", "") or ""
    enclosing_ln = row.get("enclosing_lines", "") or ""
    enclosing_kind = row.get("enclosing_kind", "") or ""
    rule_key = row.get("rule_key", "") or ""
    rule_name = row.get("rule_name", "") or ""
    rule_desc = row.get("rule_description", "") or ""
    severity = row.get("severity", "") or ""
    commit_sha = row.get("commit_sha", "") or ""
    sonar_msg = row.get("sonar_message", "") or ""
    sonar_issue_url = row.get("sonar_issue_url", "") or ""
    classification = (outputs.get("classification") or "").lower()
    confidence = (outputs.get("confidence") or "").lower()
    impact_md = (outputs.get("impact_analysis_markdown") or "").strip()
    suggested_fix = (outputs.get("suggested_fix_markdown") or "").strip()
    suggested_diff = (outputs.get("suggested_diff") or "").strip()

    # Build URLs
    sonar_public_url = _replace_sonar_url(
        sonar_issue_url, args.sonar_host_url, args.sonar_public_url
    )
    blob_url = _gitlab_blob_url(
        args.gitlab_public_url, args.gitlab_project, args.gitlab_branch,
        rel_path, line_int,
    )
    commit_url = _gitlab_commit_url(
        args.gitlab_public_url, args.gitlab_project, commit_sha
    )

    # ─ 0. Action Verdict signal ──────────────────────────────────────────
    diag = row.get("rag_diagnostic") or {}
    citation = (diag.get("citation") or {}) if diag else {}
    verdict_emoji, verdict_label, verdict_basis = _action_verdict(
        severity, classification, confidence,
        citation.get("cited_count", 0) or 0,
        citation.get("total_used", 0) or 0,
    )
    verdict_block = (
        f"> ## {verdict_emoji} {verdict_label}\n"
        f"> {verdict_basis}\n"
        f"> _(severity={severity or '—'} · classification={classification or '—'} · confidence={confidence or '—'})_"
    )

    # ─ 1. What is the problem ────────────────────────────────────────────
    # Take the first line of the LLM impact as a PM one-liner. Fall back to sonar_message when empty.
    one_line = ""
    if impact_md:
        for ln in impact_md.splitlines():
            s = ln.strip()
            if s and not s.startswith("#"):
                one_line = s
                break
    if not one_line:
        one_line = sonar_msg or rule_name or "(no impact analysis)"
    # Truncate if too long
    if len(one_line) > 240:
        one_line = one_line[:237] + "..."
    what_section = f"### 📌 What is the problem\n\n{one_line}"

    # ─ 2. Where does it happen ───────────────────────────────────────────
    location_natural = _location_natural_text(rel_path, line_int, enclosing_fn, enclosing_kind)
    static_ctx = _format_static_context_pm(row)
    where_section = "### 🎯 Where does it happen\n\n" + location_natural
    if static_ctx:
        where_section += "\n\n" + static_ctx

    # ─ 3. Impact and reasons ─────────────────────────────────────────────
    if impact_md:
        impact_section = f"### ⚠️ Impact and reasons\n\n{impact_md}"
    else:
        impact_section = "### ⚠️ Impact and reasons\n\n_(LLM did not provide impact analysis)_"

    # ─ 4. How to fix ─────────────────────────────────────────────────────
    # Hard guard against duplicate body content — deterministic enforcement
    # of prompt "case A". When suggested_diff is filled, strip the code-fence
    # block from suggested_fix_markdown so only the natural-language
    # explanation remains. Even if the LLM violates the prompt rule, the
    # body never renders the same code twice. After fence strip, if no
    # natural language remains, the entry is automatically excluded by the
    # truthy check below.
    diff_present = bool(suggested_diff) and suggested_diff.lower() not in ("null", "none")
    if diff_present and suggested_fix:
        suggested_fix = re.sub(r"```[\s\S]*?```", "", suggested_fix).strip()

    fix_blocks = []
    if suggested_fix:
        if "```" not in suggested_fix:
            lines = suggested_fix.splitlines()
            diff_count = sum(1 for ln in lines if ln.startswith(("+ ", "- ", "+", "-")))
            lang = "diff" if diff_count >= 2 else "python"
            suggested_fix = f"```{lang}\n{suggested_fix}\n```"
        fix_blocks.append(suggested_fix)
    if diff_present:
        if "```" not in suggested_diff:
            suggested_diff = f"```diff\n{suggested_diff}\n```"
        fix_blocks.append("**Machine-applicable diff:**\n\n" + suggested_diff)
    fix_section = ""
    if fix_blocks:
        fix_section = "### 🛠️ How to fix\n\n" + "\n\n".join(fix_blocks)

    # ─ 5. AI judgment basis (Phase C new) ────────────────────────────────
    ai_basis = _format_ai_basis_pm(row)
    basis_section = ""
    if ai_basis:
        basis_section = "### 🔍 AI judgment basis\n\n" + ai_basis

    # ─ 6. Other locations of the same pattern (conditional) ──────────────
    affected = row.get("affected_locations") or []
    aff_section = ""
    if affected:
        rows_md = ["| File | Line | Sonar Key |", "|------|------|-----------|"]
        for a in affected[:20]:
            comp = a.get("component") or a.get("relative_path") or ""
            lno = a.get("line") or ""
            skey = a.get("sonar_issue_key") or ""
            rows_md.append(f"| `{comp}` | {lno} | `{skey}` |")
        aff_section = (
            f"### 📂 Other locations of the same pattern ({len(affected)})\n\n"
            + "\n".join(rows_md)
        )

    # ─ 7. Technical detail (collapsed) ───────────────────────────────────
    # Code block + full rule + location table + all links — all inside the collapsed block.
    # GitLab recognizes the HTML <details> tag inside markdown.
    snippet = _trim_code_snippet(
        row.get("code_snippet", "") or "", line_int, context=10
    )
    code_block = ""
    if snippet and snippet != "(Code not found in SonarQube)":
        code_block = "**Problem code:**\n\n```\n" + snippet + "\n```"

    file_cell = f"[`{rel_path}:{line_int}`]({blob_url})" if blob_url else (
        f"`{rel_path}:{line_int}`" if rel_path else "(unknown)"
    )
    fn_cell = (
        f"`{enclosing_fn}`" + (f" *(line {enclosing_ln})*" if enclosing_ln else "")
        if enclosing_fn else "—"
    )
    rule_cell = f"`{rule_key}`" + (f" · {rule_name}" if rule_name else "")
    commit_cell = (
        f"[`{_short_sha(commit_sha)}`]({commit_url})"
        if commit_url and commit_sha
        else (f"`{_short_sha(commit_sha)}`" if commit_sha else "—")
    )
    loc_table = (
        "**Metadata:**\n\n"
        "| Field | Value |\n"
        "|------|-----|\n"
        f"| File | {file_cell} |\n"
        f"| Function | {fn_cell} |\n"
        f"| Rule | {rule_cell} |\n"
        f"| Severity | `{severity or '—'}` |\n"
        f"| Commit | {commit_cell} |"
    )

    rule_full = ""
    if rule_desc:
        # English polish via Ollama gemma4 — rule_key cache + falls back to original on failure.
        # User decision: do not show the original English in the GitLab issue (available via the SonarQube link).
        translated = _translate_rule_to_english(
            rule_key, rule_desc,
            ollama_base_url=getattr(args, "ollama_base_url", "") or "",
            ollama_model=getattr(args, "ollama_model", "") or "",
        )
        rule_full = f"**Rule full description:**\n\n{translated.strip()}"

    link_lines = []
    if sonar_public_url:
        link_lines.append(f"- [SonarQube issue detail]({sonar_public_url})")
    if blob_url:
        line_suffix = f" (line {line_int})" if line_int else ""
        link_lines.append(f"- [GitLab file{line_suffix}]({blob_url})")
    if commit_url:
        link_lines.append(f"- [GitLab commit `{_short_sha(commit_sha)}`]({commit_url})")
    links_block = ""
    if link_lines:
        links_block = "**Links:**\n\n" + "\n".join(link_lines)

    detail_inner_parts = [p for p in (loc_table, code_block, rule_full, links_block) if p]
    technical_section = ""
    if detail_inner_parts:
        inner = "\n\n".join(detail_inner_parts)
        technical_section = (
            "<details><summary>📖 Technical detail (for developers — code / rule / links)</summary>\n\n"
            + inner + "\n\n</details>"
        )

    # ─ 8. footer ─────────────────────────────────────────────────────────
    analysis_mode = getattr(args, "analysis_mode", "") or ""
    scan_label = f" ({analysis_mode} scan)" if analysis_mode else ""
    footer_parts = []
    if commit_sha:
        footer_parts.append(f"commit: `{_short_sha(commit_sha)}`{scan_label}")
    if sonar_public_url:
        footer_parts.append(f"sonar: {sonar_public_url}")
    footer = ""
    if footer_parts:
        footer = "---\n_" + " · ".join(footer_parts) + "_"

    # Assembly
    sections = [verdict_block, what_section, where_section, impact_section]
    for s in (fix_section, basis_section, aff_section, technical_section):
        if s:
            sections.append(s)
    body = "\n\n---\n\n".join(sections)
    if footer:
        body = body + "\n\n" + footer
    body = _replace_sonar_url(body, args.sonar_host_url, args.sonar_public_url)
    return body


def _find_existing_by_sonar_key(gitlab_host_url: str, headers: dict, project: str, key: str) -> bool:
    """
    Check whether GitLab already has an issue registered with the same SonarQube issue key.

    Critical helper to prevent duplicate issue creation. Even when running
    the pipeline repeatedly, the same issue does not get registered multiple
    times.

    Args:
        gitlab_host_url: GitLab host URL
        headers: PRIVATE-TOKEN auth header
        project: GitLab project path (e.g. "mygroup/myproject")
        key: SonarQube issue unique key

    Returns:
        bool: True if an existing issue is found, False otherwise
    """
    if not key: return False
    url = f"{gitlab_host_url.rstrip('/')}/api/v4/projects/{quote(project, safe='')}/issues?search={key}"
    try:
        arr = _http_get_json(url, headers)
        return isinstance(arr, list) and len(arr) > 0
    except Exception:
        return False

def main() -> int:
    """
    Main entry point: read LLM analysis output and auto-create GitLab issues.

    [Overall flow]
    1. Parse CLI args (GitLab connection info, SonarQube URL mapping, ...)
    2. Load analysis results from llm_analysis.jsonl line by line
    3. For each entry:
       a. Build issue title: "[severity] sonar message" (falls back to LLM title when missing)
       b. Replace SonarQube URLs in the description with the externally accessible URL
       c. Search GitLab for the same issue key → skip if it exists
       d. Create the GitLab issue (including the LLM-suggested labels)
    4. Save create/skip/fail results to a JSON file

    Returns:
        int: 2 if any issue failed, otherwise 0 (reflected in the Jenkins build status)
    """
    # ---------------------------------------------------------------
    # [Step 1] Parse CLI args
    # ---------------------------------------------------------------
    ap = argparse.ArgumentParser()
    ap.add_argument("--gitlab-host-url", required=True)   # GitLab internal host URL (for API calls)
    ap.add_argument("--gitlab-token", required=True)       # GitLab Personal Access Token
    ap.add_argument("--gitlab-project", required=True)     # target project path
    ap.add_argument("--input", default="llm_analysis.jsonl")     # input file (LLM analysis result)
    ap.add_argument("--output", default="gitlab_issues_created.json")  # result summary file
    ap.add_argument("--sonar-host-url", default="")        # SonarQube internal URL (replacement source)
    ap.add_argument("--sonar-public-url", default="")      # SonarQube external URL (replacement target)
    ap.add_argument("--timeout", type=int, default=60)     # API request timeout (seconds)
    # Step R new — public URL used for blob/commit links in the body.
    # Defaults to the docker-compose host mapping (28090:80).
    ap.add_argument("--gitlab-public-url", default="http://localhost:28090")
    ap.add_argument("--gitlab-branch", default="main")
    ap.add_argument("--commit-sha", default="")            # fallback when missing on the row
    # Step D — Sonar token used for the FP transition API call. Injected from a Jenkins credential.
    # When empty, the FP transition is skipped entirely (the GitLab issue is still created normally).
    ap.add_argument("--sonar-token", default="")
    # Step D — used by the footer's `(<mode> scan)` notation. Forwarded by the chained job.
    ap.add_argument("--analysis-mode", default="")
    # Rule description English polish (Ollama gemma4). When empty, the polish is
    # skipped → original (English) is kept. Cached in a dict keyed by rule_key
    # so the same rule is called only once.
    ap.add_argument("--ollama-base-url", default="",
                    help="Ollama API base URL (e.g. http://host.docker.internal:11434). "
                         "When empty, rule polishing is skipped.")
    ap.add_argument("--ollama-model", default="gemma4:e4b",
                    help="Ollama model name (used for rule polishing)")
    args = ap.parse_args()

    # GitLab API auth header
    headers = {"PRIVATE-TOKEN": args.gitlab_token}

    # Categorize processing results — including Step D Dual-path FP aggregation.
    created, skipped, failed = [], [], []
    fp_transitioned = []        # Sonar transition succeeded → no GitLab issue
    fp_transition_failed = []   # transition failed → GitLab issue created (distinguished by label)
    rows = []

    # ---------------------------------------------------------------
    # [Step 2] Load the JSONL input file
    # Each line is one JSON object, parse line by line.
    # ---------------------------------------------------------------
    try:
        with open(args.input, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip(): rows.append(json.loads(line))
    except Exception as e:
        print(f"[ERROR] Read failed: {e}", file=sys.stderr)
        return 2

    # ---------------------------------------------------------------
    # [Step 3] Walk through each analysis entry and create a GitLab issue
    # ---------------------------------------------------------------
    for row in rows:
        sonar_key = row.get("sonar_issue_key")
        outputs = row.get("outputs") or {}  # LLM output produced by the Dify workflow

        # --- 3-a. Decide the issue title ---
        # Prefer the original SonarQube message. Fall back to the LLM title when missing.
        msg = row.get("sonar_message") or ""
        llm_title = outputs.get("title") or ""
        main_title = msg if msg else llm_title

        # Prefix the severity tag for visual prioritization.
        severity = row.get("severity") or ""
        final_title = f"[{severity}] {main_title}" if severity else main_title

        # Step D — extract classification/confidence from LLM outputs (analyzer injects defaults).
        classification = (outputs.get("classification") or "true_positive").lower()
        confidence = (outputs.get("confidence") or "").lower()
        llm_skipped = bool(row.get("llm_skipped"))

        # --- 3-b. Step D: Dual-path FP processing ---
        # When classification == "false_positive", try the Sonar transition API first.
        # Success: skip GitLab issue creation, record in the aggregate.
        # Failure (or empty --sonar-token): still create the GitLab issue with the `fp_transition_failed` label.
        extra_labels = []
        if classification == "false_positive":
            # Attach fp_reason as a Sonar UI comment (right before transition — even on failure the transition still proceeds).
            # Lets the analyst see the LLM's false-positive judgment basis directly in the Sonar UI.
            fp_reason = (outputs.get("fp_reason") or "").strip()
            if fp_reason:
                comment = (
                    f"[Auto-FP by LLM · confidence={confidence or 'n/a'}]\n"
                    f"{fp_reason}"
                )
                ok_c, err_c = _sonar_add_comment(
                    args.sonar_host_url, args.sonar_token, sonar_key, comment
                )
                if not ok_c:
                    print(f"[FP-COMMENT:WARN] {sonar_key} — {err_c}")
            ok, err = _sonar_mark_fp(args.sonar_host_url, args.sonar_token, sonar_key)
            if ok:
                print(f"[FP-TRANSITION] {sonar_key} → Sonar marked as false positive")
                fp_transitioned.append({"key": sonar_key, "title": final_title})
                continue
            print(f"[FP-TRANSITION:FAIL] {sonar_key} — {err} — creating GitLab issue anyway")
            fp_transition_failed.append({"key": sonar_key, "err": err})
            extra_labels.append("fp_transition_failed")

        # --- 3-c. Deterministic body render (includes Step R + Step D extensions) ---
        # Override row's commit_sha with --commit-sha (CLI) when empty.
        if not row.get("commit_sha"):
            row["commit_sha"] = args.commit_sha or ""
        desc = render_issue_body(row, args)

        # If the title is empty, cannot create. The body renderer guarantees minimum sections (location + impact).
        if not final_title:
            failed.append({"key": sonar_key, "reason": "Empty title"})
            continue

        # --- 3-d. Duplicate check ---
        if _find_existing_by_sonar_key(args.gitlab_host_url, headers, args.gitlab_project, sonar_key):
            skipped.append({"key": sonar_key, "title": final_title, "reason": "Dedup"})
            continue

        # --- 3-e. Create the GitLab issue ---
        form = {"title": final_title, "description": desc}
        form["labels"] = _merge_labels(
            llm_labels=outputs.get("labels"),
            severity=severity,
            classification=classification,
            confidence=confidence,
            llm_skipped=llm_skipped,
            extra=extra_labels,
        )

        url = f"{args.gitlab_host_url.rstrip('/')}/api/v4/projects/{quote(args.gitlab_project, safe='')}/issues"
        try:
            status, body = _http_post_form(url, headers, form, args.timeout)
            if status in (200, 201):
                # The 04 build report's §3 module table can build GitLab direct
                # links (`/-/issues/{iid}`), so extract iid from the response body
                # and include it in the entry.
                # Even if extraction fails, the entry is still recorded as
                # successfully registered (just without iid).
                iid = None
                try:
                    iid = json.loads(body).get("iid")
                except Exception:
                    pass
                entry = {"key": sonar_key, "title": final_title}
                if iid is not None:
                    entry["iid"] = iid
                created.append(entry)
            else:
                failed.append({"key": sonar_key, "status": status, "body": body})
        except Exception as e:
            failed.append({"key": sonar_key, "err": str(e)})

    # ---------------------------------------------------------------
    # [Step 4] Save the result summary file
    # Visible in the Jenkins console and artifacts for status checking.
    # ---------------------------------------------------------------
    summary = {
        "created": created,
        "skipped": skipped,
        "failed": failed,
        "fp_transitioned": fp_transitioned,
        "fp_transition_failed": fp_transition_failed,
    }
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print(
        f"[OK] created={len(created)} skipped={len(skipped)} failed={len(failed)} "
        f"fp_transitioned={len(fp_transitioned)} fp_transition_failed={len(fp_transition_failed)} "
        f"output={args.output}"
    )
    # Return code 2 when there are failures — Jenkins shows the build as UNSTABLE/FAILURE.
    return 2 if failed else 0

if __name__ == "__main__":
    sys.exit(main())
