sonar.projectKey=nodegoat
sonar.projectName=nodegoat
sonar.sources=app,config,server.js
sonar.tests=test
sonar.test.inclusions=test/**/*.js
sonar.exclusions=**/node_modules/**,**/artifacts/**,**/.github/**,**/cypress/**
sonar.sourceEncoding=UTF-8
