import ast
import json
import os
import re
import logging

log = logging.getLogger(__name__)


def convert_playwright_to_dsl(file_path: str, output_dir: str) -> list[dict]:
    """
    Parse a Python script generated by Playwright codegen and convert it into
    a 14-action DSL scenario.json.

    Mapping:
      9 actions (pre-Sprint 2): navigate, wait, click, fill, press, select, check, hover, verify
      5 added in Sprint 4C:
        - upload      ← page.locator(...).set_input_files("path")
        - drag        ← page.locator(src).drag_to(page.locator(dst))
        - scroll      ← page.locator(...).scroll_into_view_if_needed()
        - mock_status ← page.route("PATTERN", lambda r: r.fulfill(status=NN))
        - mock_data   ← page.route("PATTERN", lambda r: r.fulfill(... body=...))

    Usage:
      playwright codegen https://target-app.com --output recorded.py
      python3 -m zero_touch_qa --mode convert --file recorded.py

    Implementation (T-A / P0.4): two-stage strategy, AST first + line fallback.
      1) zero_touch_qa.converter_ast.convert_via_ast — converts popup / .nth /
         .first / .filter / frame_locator chains losslessly.
      2) If AST raises (non-standard lambdas / dynamic patterns / SyntaxError),
         fall back to the line-based path — safety net.
    """
    if not file_path or not os.path.exists(file_path):
        raise FileNotFoundError(f"file not found: {file_path}")

    # 1) AST first
    try:
        from .converter_ast import convert_via_ast, CodegenAstError
        scenario = convert_via_ast(file_path, output_dir)
        if scenario:
            return scenario
        log.warning(
            "[Convert] AST result was empty — trying line fallback. file=%s",
            file_path,
        )
    except CodegenAstError as e:
        log.warning("[Convert] AST conversion failed — line fallback. reason: %s", e)
    except FileNotFoundError:
        raise
    except Exception as e:  # noqa: BLE001
        log.warning(
            "[Convert] AST raised — line fallback. type=%s msg=%s",
            type(e).__name__, e,
        )

    # 2) line fallback (legacy)
    return _convert_via_lines(file_path, output_dir)


def _convert_via_lines(file_path: str, output_dir: str) -> list[dict]:
    """Line-based regex conversion (legacy). Safety net when AST conversion fails.

    Not used while AST conversion works. The caller falls back here only when
    AST returns empty or raises.
    """
    with open(file_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    scenario = []
    step_num = 0

    skip_keywords = (
        "import ", "from ", "def ", "with ", "browser", "context",
        "try:", "finally:", "if __name__", "print(", "# ---",
        '"""', "'''",
    )

    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if any(line.startswith(k) for k in skip_keywords):
            continue
        # codegen binds popup / new-tab actions to page1, page2, … via
        # `with page.expect_popup() as page1_info` → `page1.click(...)`.
        # The executor watches context.pages after every step and switches the active
        # page automatically (executor.py:166-201), so the scenario can be flattened
        # into a single page sequence with identical behavior.
        # The AST core (T-A) usually handles this, so this line never runs in practice;
        # kept as the fallback safety net.
        line = re.sub(r"\bpage\d+\.", "page.", line)
        if not (line.startswith("page.") or line.startswith("expect(")):
            continue

        step = _parse_playwright_line(line)
        if step:
            step_num += 1
            step["step"] = step_num
            step.setdefault("fallback_targets", [])
            scenario.append(step)

    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "scenario.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(scenario, f, indent=2, ensure_ascii=False)

    log.info(
        "[Convert/line-fallback] %s -> %s (%d steps converted)",
        file_path, output_path, step_num,
    )
    return scenario


def _parse_playwright_line(line: str) -> dict | None:
    """Convert a single Playwright code line into a DSL step."""

    # navigate
    m = re.search(r'page\.goto\(["\'](.+?)["\']\)', line)
    if m:
        return {
            "action": "navigate", "target": "", "value": m.group(1),
            "description": f"navigate to {m.group(1)}",
        }

    # wait
    m = re.search(r'page\.wait_for_timeout\((\d+)\)', line)
    if m:
        return {
            "action": "wait", "target": "", "value": m.group(1),
            "description": f"wait {m.group(1)}ms",
        }

    # wait_for_load_state / wait_for_url are auxiliary to navigate
    if "wait_for_load_state" in line or "wait_for_url" in line:
        return None

    # mock_status / mock_data — page.route("PATTERN", lambda r: r.fulfill(...))
    # Priority: no token collision with the other actions, so handle before page.locator matching.
    if "page.route(" in line and "fulfill" in line:
        mock_step = _parse_mock_route(line)
        if mock_step is not None:
            return mock_step

    target = _extract_target(line)

    # fill
    m = re.search(r'\.fill\(["\'](.+?)["\']\)', line)
    if m:
        return {
            "action": "fill", "target": target, "value": m.group(1),
            "description": f"fill '{m.group(1)}'",
        }

    # press
    m = re.search(r'\.press\(["\'](.+?)["\']\)', line)
    if m:
        return {
            "action": "press", "target": target, "value": m.group(1),
            "description": f"press {m.group(1)}",
        }

    # select_option
    m = re.search(r'\.select_option\((?:label=)?["\'](.+?)["\']\)', line)
    if m:
        return {
            "action": "select", "target": target, "value": m.group(1),
            "description": f"select '{m.group(1)}'",
        }

    # check / uncheck
    if ".uncheck()" in line:
        return {
            "action": "check", "target": target, "value": "off",
            "description": "uncheck",
        }
    if ".check()" in line:
        return {
            "action": "check", "target": target, "value": "on",
            "description": "check",
        }

    # hover
    if ".hover()" in line:
        return {
            "action": "hover", "target": target, "value": "",
            "description": "hover",
        }

    # upload — set_input_files("path") or set_input_files(["a", "b"]) (first item)
    m = re.search(r'\.set_input_files\(\s*\[\s*["\'](.+?)["\']', line)
    if m:
        return {
            "action": "upload", "target": target, "value": m.group(1),
            "description": f"upload '{m.group(1)}'",
        }
    m = re.search(r'\.set_input_files\(\s*["\'](.+?)["\']\s*\)', line)
    if m:
        return {
            "action": "upload", "target": target, "value": m.group(1),
            "description": f"upload '{m.group(1)}'",
        }

    # drag — page.locator(src).drag_to(page.locator(dst))
    if ".drag_to(" in line:
        dst_target = _extract_drag_destination(line)
        if dst_target:
            return {
                "action": "drag", "target": target, "value": dst_target,
                "description": "drag and drop",
            }

    # scroll — scroll_into_view_if_needed
    if "scroll_into_view_if_needed" in line:
        return {
            "action": "scroll", "target": target, "value": "into_view",
            "description": "scroll into view",
        }

    # click (checked last so it doesn't shadow other actions)
    if ".click(" in line or line.endswith(".click()"):
        return {
            "action": "click", "target": target, "value": "",
            "description": "click",
        }

    # expect → verify
    m = re.search(r'expect\((.+?)\)\.to_have_text\(["\'](.+?)["\']\)', line)
    if m:
        verify_target = _extract_target(m.group(1))
        return {
            "action": "verify", "target": verify_target, "value": m.group(2),
            "description": f"verify text '{m.group(2)}'",
        }

    m = re.search(r'expect\((.+?)\)\.to_be_visible', line)
    if m:
        verify_target = _extract_target(m.group(1))
        return {
            "action": "verify", "target": verify_target, "value": "",
            "description": "verify visible",
        }

    return None


def _extract_target(line: str) -> str:
    """Extract the DSL target string from Playwright locator code."""

    # get_by_role("button", name="Sign in")
    m = re.search(
        r'get_by_role\(["\'](.+?)["\'],\s*name=["\'](.+?)["\'](?:\s*,[^)]*)?\)',
        line,
    )
    if m:
        return f"role={m.group(1)}, name={m.group(2)}"

    # get_by_role("heading") (no name)
    m = re.search(r'get_by_role\(["\'](.+?)["\']\)', line)
    if m and "name=" not in line.split("get_by_role")[1].split(")")[0]:
        return f"role={m.group(1)}"

    # get_by_label
    m = re.search(r'get_by_label\(["\'](.+?)["\']\)', line)
    if m:
        return f"label={m.group(1)}"

    # get_by_text
    m = re.search(r'get_by_text\(["\'](.+?)["\']\)', line)
    if m:
        return f"text={m.group(1)}"

    # get_by_placeholder
    m = re.search(r'get_by_placeholder\(["\'](.+?)["\']\)', line)
    if m:
        return f"placeholder={m.group(1)}"

    # get_by_test_id
    m = re.search(r'get_by_test_id\(["\'](.+?)["\']\)', line)
    if m:
        return f"testid={m.group(1)}"

    # page.locator("css-selector")
    m = re.search(r'page\.locator\(["\'](.+?)["\']\)', line)
    if m:
        return m.group(1)

    return ""


def _extract_drag_destination(line: str) -> str:
    """Extract the dst locator expression from `.drag_to(<expr>)` and convert it to a DSL target."""
    idx = line.find(".drag_to(")
    if idx < 0:
        return ""
    # Position right after `(`
    start = idx + len(".drag_to(")
    depth = 1
    i = start
    while i < len(line) and depth > 0:
        c = line[i]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                break
        i += 1
    inner = line[start:i]
    # `inner` is typically `page.locator("...")` / `page.get_by_role("...", name="...")` etc.
    # _extract_target handles the same patterns, so delegate. Optional args like timeout=,
    # force= follow the first expression after a comma, but the regexes inside
    # _extract_target match only the first occurrence, so they pass through unchanged.
    return _extract_target(inner)


def _parse_mock_route(line: str) -> dict | None:
    """Convert `page.route("PATTERN", lambda r: r.fulfill(...))` into mock_status / mock_data."""
    m_pat = re.search(r'page\.route\(\s*["\'](.+?)["\']', line)
    if not m_pat:
        return None
    pattern = m_pat.group(1)

    # If body=... is present → mock_data; otherwise if status=NN only → mock_status.
    m_body = re.search(r'body\s*=\s*([^,)]+(?:\([^)]*\))?[^,)]*)', line)
    if m_body:
        body_expr = m_body.group(1).strip()
        # If it's a quoted string, decode Python escapes and use as the value.
        # `body="{\"items\":[]}"` → `{"items":[]}` so the regression_generator emitter
        # (`json.dumps(str(value))`) and the mock-route fulfill body stay 1:1 consistent.
        body_value = body_expr
        if re.match(r'^["\'].*["\']$', body_expr):
            try:
                body_value = ast.literal_eval(body_expr)
            except (ValueError, SyntaxError):
                body_value = body_expr.strip("\"'")
        return {
            "action": "mock_data", "target": pattern, "value": body_value,
            "description": f"mock response body for {pattern}",
        }

    m_status = re.search(r'status\s*=\s*(\d+)', line)
    if m_status:
        return {
            "action": "mock_status", "target": pattern, "value": m_status.group(1),
            "description": f"mock response status {m_status.group(1)} for {pattern}",
        }
    return None
